### ISSUE TITLE
Code Quality: prevent needing to update each content update

### ISSUE THREAD

**Issue by harbingerofme** [lodsharpshooter/RoRCheats#1]
https://github.com/lodsharpshooter/RoRCheats/blob/b8213a1e517162ffc2feba81b59309e553767fbe/Source/Main.cs#L795
https://github.com/lodsharpshooter/RoRCheats/blob/b8213a1e517162ffc2feba81b59309e553767fbe/Source/Main.cs#L811
These lines will become outdated with game updates and are incompatible with custom item mods, consider using `ItemCatalog.itemCount`;

**Comment by Lodington** [comment]
Allset thank you harb!
